# Vagrant boxes use eth1 interface for internal communication
---
- hosts: all
  become: yes
  tasks:
    - debug:
        msg: "System {{ inventory_hostname }} {{ ansible_eth1.ipv4.address }}"
    - name: Install list of packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
            - curl
            - iproute2
            - python3
            - netcat
            - python3-pip
    - pip:
        name: pip
        state: latest
        executable: pip3
    - pip:
        name: tcconfig
        state: latest
        executable: pip3
    - copy: 
        src: "dist-example"
        dest: "/usr/bin/dist-example"
        mode: 0755